### ISSUE TITLE
Upgrade to Elm 0.14.x

### ISSUE THREAD

**Issue by madsflensted** [lambdatoast/elm.vim#15]
I was looking into how to upgrade this plugin to support the new executable names in 0.14.x, but it seems that some of the functionality is not longer present in elm (like the --print-types).

Is there another way to support that release?

**Comment by lambdatoast** [comment]
Oh crap. Yes. Elm's compilation functionality has been split into a couple of different binaries. So all of this plugin's functionality is pretty much broken due to that.

Thanks for reminding me. I'll update things to support Elm's latest model.

**Comment by madsflensted** [comment]
Great,  let me know if I can help or test.

**Comment by etaque** [comment]
Hi, I'm also interested in 0.14 upgrade :)

**Comment by hoosierEE** [comment]
Elm is 0.15 now, see #21

**Comment by hoosierEE** [comment]
I think this can be closed now.

**Comment by madsflensted** [comment]
Great work @hoosierEE .
