### ISSUE TITLE
Type inference

### ISSUE THREAD

**Issue by gyzerok** [lambdatoast/elm.vim#23]
It would be awesome to add an ability to see type of a particular expression

**Comment by gabrielflorit** [comment]
@gyzerok You might find this of use: [https://github.com/ElmCast/elm-vim](https://github.com/ElmCast/elm-vim) has this built in. Type `:ElmShowDocs` when over a token (e.g. `Signal` below) and you get lots of useful information:

<img width="734" alt="screen shot 2016-02-08 at 2 18 44 am" src="https://cloud.githubusercontent.com/assets/370976/12880078/97906328-ce0a-11e5-8996-8512911b21ec.png">

**Comment by gyzerok** [comment]
Oh, sorry, I've mention ability to see this for my custom code.

```elm
search : String -> Query -> Effects (Maybe Response)
search endpoint query =
    let url = Http.url ("http://example.com" ++ endpoint)
            [ ( "key", "onlinedev" )
            , ( "q", query.q )
            , ( "region_id", "1" )
            ]
    in
        Http.get decode url
            |> Task.toMaybe -- Show me type here
            |> Effects.task
```

**Comment by gyzerok** [comment]
I'm talking not about `Task.toMaybe` docs but about concrete return type after execution of this line

**Comment by gyzerok** [comment]
Maybe next example would better show my idea

```elm
search endpoint query = -- :type = String -> Query -> Effects (Maybe Response)
    let url = Http.url ("http://example.com" ++ endpoint)
            [ ( "key", "onlinedev" )
            , ( "q", query.q )
            , ( "region_id", "1" )
            ]
    in
        Http.get decode url
            |> Task.toMaybe -- Show me type here
            |> Effects.task
```
